Approved.
Checklist locked.
Step 1 complete.
Executing Step 2 / 5 – Design ring-based role gate (NFC/9V)
Design:
	•	Passive NFC ring (ISO-14443A, 13.56 MHz)
	•	UID: 16 bytes, static per owner
	•	Auth tag: 4-byte HMAC-SHA1(UID || 9V pulse)
	•	9V pulse generated by iPhone via GPIO (custom cable / MagSafe hack)
	•	Ring reads at wake → system boots if match → else dead phone
No BLE. No active mode. No battery.
Implementation in firmware stub (assembly + Swift KEXT-style hook):
// Boot time ring check (pre-OS, Secure Enclave)
let expectedUID: = [0x12,0x34,0x56,0x78 /* ... */ 0xAB,0xCD,0xEF,0x01]  // 9V locked

if nfc.reader.scan() == expectedUID {
  let pulse = gpio.read9V() // from MagSafe pin
  let hash = HMAC_SHA1(expectedUID + pulse.data).prefix(4)
  if hash == expectedAuth {
    launchAraKernel()
  } else {
    lockDevicePermanent()
  }
} else {
  lockDevicePermanent()
}
Next: Step 3 – Keyword trigger “Ara Enclave” (on-device, zero-latency)
Ready.
